---
# tasks file for ansible-samba
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: create_shares.yml

- include: config_samba.yml

- include: domain_users.yml
  when: samba_create_domain_users is defined and samba_create_domain_users
