---

# handlers file for ansible-samba
- name: restart smbd
  service:
    name: "{{ smb_service }}"
    state: "{{ 'restarted' if not samba_server_role == 'active directory domain controller' else 'stopped' }}"
    enabled: "{{ 'no' if not samba_server_role == 'active directory domain controller' else 'yes' }}"

- name: restart nmbd
  service:
    name: "{{ nmb_service }}"
    state: "{{ 'restarted' if not samba_server_role == 'active directory domain controller' else 'stopped' }}"
    enabled: "{{ 'no' if not samba_server_role == 'active directory domain controller' else 'yes' }}"

- name: restart winbind
  service:
    name: "{{ winbind_service }}"
    state: "{{ 'restarted' if not samba_server_role == 'active directory domain controller' else 'stopped' }}"
    enabled: "{{ 'no' if not samba_server_role == 'active directory domain controller' else 'yes' }}"

- name: restart samba-ad-dc
  service:
    name: "{{ ad_dc_service }}"
    state: "{{ 'restarted' if samba_server_role == 'active directory domain controller' else 'stopped' }}"
    enabled: "{{ 'yes' if samba_server_role == 'active directory domain controller' else 'no' }}"
  when: ansible_os_family == "Debian"
